Create database Cb_Analysis
Use Cb_Analysis
Select Top 10 * From [dbo].[customer_data]
-----------------------------------------------------------------------------------------------------------------------------
-- Business Insight Question
---------------------------------------------------------------------------------------------------------------------
--1. Which Category generates highest Revenue
Select
   category,
   Round(Sum(purchase_amount),2) as highest_revenue
   From [dbo].[customer_data]
   Group by category
   Order by  highest_revenue desc;

   --?.Business problem:- Company does not know which category most to revenue.
   -- impact - 
            -- Helps priortize high performing categories
            -- optimizes inventory planning
            -- Improves marketing ROI
---------------------------------------------------------------------------------------

--2.Are Discount actually increases Purchase value
Select * From customer_data

Select discount_applied,
Round(Sum(purchase_amount),2) as Total_revenue,
Round(Avg(purchase_amount),2) as Avg_Purchase
From customer_data
group by discount_applied;

--?.Business Problem:- Discount may Reduce Profit without increasing sales
    
--Impact
          --Identify effectiveness of Discount 
          --Reduce Unnecessary discount cost
          --Improve profit margin
--------------------------------------------------------------------------------------------
--3.What is the total revenue generated by Male & Female
Select * From customer_data;

Select gender,
      Round(Sum(purchase_amount),2) as highest_revenue
      From customer_data
      Group by gender
      Order by highest_revenue;

--Business Problem :- lack of understanding of revenue contribution by gender segment.

--impact
        --Help targetting marketing campaign.
        --improve customer segment strategy.
        --Enhances personalization efforts.

-------------------------------------------------------------------------------------------------------
--4.Which customer used a  discount but still spent more than the purchase amount?

Select * From customer_data

Select Top 10
       customer_id,
       purchase_amount,
       discount_applied
       From customer_data
Where discount_applied = 'Yes' And purchase_amount > (Select Avg(purchase_amount) From customer_data);

--Business Problem:- Company cannot find high spending customer who are also discount users.

--Impact:-
          --Identify premium discount-sensitive customer.
          --Enable target discount campaigns.
          --Improves customer retention and revenues.

-----------------------------------------------------------------------------------------------------------------
--5.Which are top/bottom 5 products with the highest average review rating?

Select * From customer_data

Select Top 5
       item_purchased,
       Round(Avg(review_rating),2) As avg_rating
From customer_data
Group by item_purchased
Order by avg_rating Desc;

Select Top 5
       item_purchased,
       Round(Avg(review_rating),2) As avg_rating
From customer_data
Group by item_purchased
Order by avg_rating Asc;

--Business Problem:- No visibility into product performance based on customer satisfaction?

--impact:- 
         --Promotes high performing Producrts.
         --improve low rated Products.
         --Enhances customer experience.
----------------------------------------------------------------------------------------------------------
--6.Average purchase:-Standard v/s Express Shipping?

Select * From customer_data

Select 
       shipping_type,
       Count(Distinct customer_id) As Order_placed,
       Round(Avg(purchase_amount),2) As avg_purchase
From customer_data
Where shipping_type IN ('Standard','Express')
Group by shipping_type;
       
--impact--
        --Help optimize sipping price strategy.
        --Encourages premium shipping adoption.
        --Increases Average order value.
------------------------------------------------------------------------------------------------------------------------------
--7.Do subscribed customer spend more?Compare average speed and total revenue between subscriber and non subscriber?
Select * From customer_data

Select
       subscription_status,
      count(customer_id) as Total_User,
      Round(Sum(purchase_amount),2) as total_revenue,
      Round(Avg(purchase_amount),2) as Avg_revenue
From customer_data
Group by subscription_status
order by total_revenue;

--Business problem:- the effectiveness of buisness program is unknown.
--impact:- 
         --Validates subscription model performance.
         --improves customer loyalty program.
         --increase customer lifetime value.
-----------------------------------------------------------------------------------------------------------------
--8.Top 5 products with highest discount usage %.
Select * from customer_data;

Select top 5
      item_purchased,
      count(item_purchased) as total_no_of_item_sold,
      count(case when discount_applied = 'Yes' then 1 end) As no_of_times_when_sold,
      count(case when discount_applied = 'Yes' then 1 end) * 100.0 / Count(*) as discount_percent
From customer_data
group by item_purchased
order by  discount_percent desc;

--Business problem:- some product may be highly depend on discount.
--impact:-
        --identifies discount driven products.
        --helps optimize price strategy.
        --Reduces profit margin loss.
-------------------------------------------------------------------------------------------------------------------------------
--9.Segment customer into new returning and loyal based on their total no of previous purchase?
---.amd show the count of each segment.

Select * from customer_data;

Select
      case 
           when previous_purchases = 0 then 'New_customer'
           when previous_purchases between 1 and 15 then 'regular_customer'
        else 'loyal_customer'
           end as customer_segment,
           count(*) as customer_count
       From customer_data
                group by case
                when previous_purchases = 0 then 'New_customer'
                when previous_purchases between 1 and 15 then 'regular_customer'
           else 'loyal_customer'
           end 

--Business Problem:- lack of customer segmentation lead to generic strategies.
--Impact:-
        --Enables personalized marketing.
        --Improves retention strategies.
        --increases conversion rates.

---------------------------------------------------------------------------------------------------------------------------------------
--10.What are the top 3 most purchased products within each category?
Select * from customer_data
with cte as
(
Select  
category,
item_purchased,
count(item_purchased) AS most_purchased,
Rank() over (partition by category order by count(item_purchased)desc) as RNK
From customer_data
group by category,item_purchased
)
Select * from cte
where RNK <=3

--Business problem:- the company doesn't know top performing products within category
--impact:- 
        --Improve product placement and recommendation.
        --Helps inventory optimization.
        --increases sales through best sellers.

------------------------------------------------------------------------------------------------------------------------------
--11.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 select * from customer_data;
 
 Select 
      case
      when previous_purchases  > 5 then 'Repeat_buyers'
      else 'Normal_buyers'
    End as  customer_type,
    subscription_status,
    count(*) As customer_count,
    count(*) * 100.0/ Sum(count(*)) over (partition by case
                                    when previous_purchases > 5 then 'Repeat_buyers'
                                    else 'Normal_buyers'
                                    End 
                                    )as percents

  From customer_data
  group by case when previous_purchases  > 5 then 'Repeat_buyers'
      else 'Normal_buyers'
    End, subscription_status

--Business Problem:- unclear relationship between loyalty and subscription.
--impact:-
        --improves subscription targetting.
        --increases conversion to paid programs.
        --increase customer retention strategy.

---------------------------------------------------------------------------------------------------------------------------------------------------
--12.What is the revenue contribution of each age group?
Select * from customer_data;

Select 
     case
         when age between 18 And 25 then '18-25'
         when age between 26 And 35 then '26-35'
         when age between 35 And 50 then '35-50'
     Else '51+'
     end as Age_Group,
     Round(Sum(purchase_amount),2) As total_revenue
From customer_data
Group by case
             
         when age between 18 And 25 then '18-25'
         when age between 26 And 35 then '26-35'
         when age between 35 And 50 then '35-50'
     Else '51+'
     end
     order by total_revenue;

--Business Problem:- No visibility into which age group contributes most to revenue
--impact
        --Enables age based targetting.
        --Enhances marketing efficiency.